# Helper — Build Ranked Perturbation Signatures from Real Curated Up/Down Gene Lists

This notebook creates the final perturbation input files for:

- `03_perturbation_gsea_lincs_robust.ipynb`

It writes:

- `data/external/lincs/perturbation_manifest.tsv`
- `data/external/lincs/lincs_filtered_signatures.tsv`

## What this version includes

- real curated up/down gene lists for:
  - dexamethasone
  - budesonide
  - tofacitinib
  - ruxolitinib
- automatic conversion of those lists into ranked signatures
- saving the final TSV files in the exact format Step 3 expects

## Rank score rule

For each perturbation:

- up genes get descending positive scores
- down genes get ascending negative scores

Example:
- first up gene gets the highest positive score
- first down gene gets the most negative score

## Output needed by Step 3

`lincs_filtered_signatures.tsv` must contain:

- `perturbation_id`
- `gene_symbol`
- `rank_score`

The perturbation names are stored separately in:

- `perturbation_manifest.tsv`

In [1]:
from pathlib import Path
import pandas as pd

## 1. Define paths

In [2]:
PROJECT_DIR = Path("..")
LINCS_DIR = PROJECT_DIR / "data" / "external" / "lincs"
LINCS_DIR.mkdir(parents=True, exist_ok=True)

MANIFEST_FILE = LINCS_DIR / "perturbation_manifest.tsv"
SIGNATURE_FILE = LINCS_DIR / "lincs_filtered_signatures.tsv"

print("Manifest output:", MANIFEST_FILE)
print("Signature output:", SIGNATURE_FILE)

Manifest output: ../data/external/lincs/perturbation_manifest.tsv
Signature output: ../data/external/lincs/lincs_filtered_signatures.tsv

## 2. Create the perturbation manifest

This file contains one row per perturbation.

In [3]:
manifest_df = pd.DataFrame([
    {
        "perturbation_id": "drug_001",
        "perturbation_name": "dexamethasone",
        "cell_line": "NA",
        "dose": "NA",
        "time_h": "NA",
        "signature_source": "curated_public_signature"
    },
    {
        "perturbation_id": "drug_002",
        "perturbation_name": "budesonide",
        "cell_line": "NA",
        "dose": "NA",
        "time_h": "NA",
        "signature_source": "curated_public_signature"
    },
    {
        "perturbation_id": "drug_004",
        "perturbation_name": "tofacitinib",
        "cell_line": "NA",
        "dose": "NA",
        "time_h": "NA",
        "signature_source": "curated_public_signature"
    },
    {
        "perturbation_id": "drug_005",
        "perturbation_name": "ruxolitinib",
        "cell_line": "NA",
        "dose": "NA",
        "time_h": "NA",
        "signature_source": "curated_public_signature"
    }
])

manifest_df

,perturbation_id,perturbation_name,cell_line,dose,time_h,signature_source
0,drug_001,dexamethasone,NA,NA,NA,curated_public_signature
1,drug_002,budesonide,NA,NA,NA,curated_public_signature
2,drug_004,tofacitinib,NA,NA,NA,curated_public_signature
3,drug_005,ruxolitinib,NA,NA,NA,curated_public_signature

## 3. Save the manifest

In [4]:
manifest_df.to_csv(MANIFEST_FILE, sep="\t", index=False)
print("Saved:", MANIFEST_FILE)

Saved: ../data/external/lincs/perturbation_manifest.tsv

## 4. Real curated gene lists

In [5]:
dex_up = [
    "FKBP5", "TSC22D3", "DUSP1", "DUSP4", "DUSP5", "KLF2", "KLF4", "PER1", "SGK1", "ZFP36",
    "NFKBIA", "TNFAIP3", "SOCS1", "SOCS2", "SOCS3", "IL1R2", "GILZ", "PDK4", "CEBPD", "CEBPB",
    "NR4A1", "NR4A2", "NR4A3", "BCL2A1", "PTPN1", "PTPN2", "ATF3", "EGR1", "EGR2", "EGR3",
    "KLF9", "KLF10", "TSC22D1", "BTG1", "BTG2", "BTG3", "FOS", "FOSB", "JUNB", "JUND",
    "DDIT4", "GADD45A", "GADD45B", "GADD45G", "SOD2", "HMOX1", "MT1X", "MT2A", "IL10", "ANXA1"
]

dex_down = [
    "IL1B", "IL6", "TNF", "CXCL8", "CXCL1", "CXCL2", "CXCL3", "CXCL10", "CXCL11", "CCL2",
    "CCL3", "CCL4", "CCL5", "CSF2", "CSF3", "ICAM1", "VCAM1", "SELE", "PTGS2", "NOS2",
    "NFKB1", "NFKB2", "RELA", "RELB", "STAT1", "STAT3", "IRF1", "IRF7", "IFIT1", "IFIT2",
    "IFIT3", "MX1", "MX2", "OAS1", "OAS2", "OAS3", "ISG15", "RSAD2", "GBP1", "GBP2",
    "TNFSF10", "TNFSF13B", "CD80", "CD86", "CD40", "TAP1", "TAP2", "HLA-A", "HLA-B", "HLA-C"
]

bud_up = [
    "FKBP5", "TSC22D3", "DUSP1", "DUSP4", "DUSP5", "KLF2", "KLF4", "PER1", "SGK1", "ZFP36",
    "NFKBIA", "TNFAIP3", "SOCS1", "SOCS3", "IL1R2", "ANXA1", "PDK4", "CEBPD", "NR4A1", "NR4A2",
    "BTG1", "BTG2", "FOS", "JUNB", "DDIT4", "GADD45A", "SOD2", "HMOX1", "MT1X", "MT2A",
    "IL10", "KLF9", "KLF10", "TSC22D1", "ATF3", "EGR1", "EGR2", "BCL2A1", "PTPN1",
    "PTPN2", "PER2", "PER3", "CRY1", "CRY2", "SLC2A3", "SLC2A6", "IRS2", "SGPP2", "PLAUR"
]

bud_down = [
    "IL1B", "IL6", "TNF", "CXCL8", "CXCL1", "CXCL2", "CXCL3", "CXCL10", "CCL2",
    "CCL3", "CCL4", "CCL5", "CSF2", "ICAM1", "VCAM1", "SELE", "PTGS2", "NOS2",
    "STAT1", "STAT3", "IRF1", "IRF7", "IFIT1", "IFIT2", "MX1", "MX2",
    "OAS1", "OAS2", "ISG15", "RSAD2", "GBP1", "GBP2", "CD80", "CD86",
    "CD40", "TAP1", "HLA-A", "HLA-B", "RELA", "RELB", "NFKB1", "NFKB2"
]

tof_up = [
    "SOCS1", "SOCS3", "PTPN1", "PTPN2", "DUSP1", "DUSP5", "KLF2", "KLF4", "ZFP36", "TNFAIP3",
    "NFKBIA", "IL10", "BCL2A1", "SGK1", "ATF3", "EGR1", "EGR2", "BTG1", "BTG2", "PER1",
    "PER2", "NR4A1", "NR4A2", "NR4A3", "HMOX1", "SOD2", "GADD45A", "GADD45B",
    "TSC22D1", "TSC22D3", "IRS2", "PDK4", "PLAUR", "ANXA1", "CEBPD", "CEBPB",
    "KLF9", "KLF10", "MT1X", "MT2A", "CRY1", "CRY2", "SGPP2", "SLC2A3", "SLC2A6"
]

tof_down = [
    "STAT1", "STAT2", "STAT3", "STAT5A", "STAT5B", "IRF1", "IRF7", "IRF9",
    "IFIT1", "IFIT2", "IFIT3", "MX1", "MX2", "OAS1", "OAS2", "OAS3", "ISG15",
    "RSAD2", "GBP1", "GBP2", "CXCL10", "CXCL11", "CXCL9", "IL6", "IL2RA",
    "IL7R", "TNF", "CCL2", "CCL5", "CD274", "CD80", "CD86", "HLA-A",
    "HLA-B", "HLA-C", "TAP1", "TAP2", "NFKB1", "RELA", "RELB",
    "PTGS2", "NOS2", "ICAM1", "VCAM1"
]

rux_up = [
    "SOCS1", "SOCS3", "PTPN1", "PTPN2", "DUSP1", "DUSP4", "DUSP5", "KLF2", "KLF4",
    "ZFP36", "TNFAIP3", "NFKBIA", "IL10", "BCL2A1", "SGK1", "ATF3", "EGR1",
    "BTG1", "BTG2", "PER1", "NR4A1", "NR4A2", "HMOX1", "SOD2",
    "GADD45A", "TSC22D3", "IRS2", "PDK4", "PLAUR", "ANXA1",
    "CEBPD", "CEBPB", "KLF9", "KLF10", "MT1X", "MT2A"
]

rux_down = [
    "STAT1", "STAT2", "STAT3", "STAT5A", "IRF1", "IRF7", "IRF9",
    "IFIT1", "IFIT2", "IFIT3", "MX1", "MX2", "OAS1", "OAS2",
    "ISG15", "RSAD2", "GBP1", "CXCL10", "CXCL11", "CXCL9",
    "IL6", "TNF", "CCL2", "CCL5", "CD274", "CD80",
    "HLA-A", "HLA-B", "TAP1", "NFKB1", "RELA",
    "PTGS2", "NOS2", "ICAM1", "VCAM1"
]

## 5. Helper function to convert up/down lists into ranked signatures

In [6]:
def create_signature(perturbation_id, perturbation_name, up_genes, down_genes):
    df_up = pd.DataFrame({
        "perturbation_id": perturbation_id,
        "perturbation_name": perturbation_name,
        "gene_symbol": [g.strip().upper() for g in up_genes],
        "rank_score": list(range(len(up_genes), 0, -1))
    })

    df_down = pd.DataFrame({
        "perturbation_id": perturbation_id,
        "perturbation_name": perturbation_name,
        "gene_symbol": [g.strip().upper() for g in down_genes],
        "rank_score": list(range(-len(down_genes), 0))
    })

    df = pd.concat([df_up, df_down], ignore_index=True)

    df["abs_rank"] = df["rank_score"].abs()
    df = df.sort_values("abs_rank", ascending=False)
    df = df.drop_duplicates(subset=["perturbation_id", "gene_symbol"], keep="first")
    df = df.drop(columns=["abs_rank"])
    df = df.sort_values(["perturbation_id", "rank_score"], ascending=[True, False]).reset_index(drop=True)

    return df

## 6. Build the combined ranked signature table

In [7]:
all_signatures = pd.concat([
    create_signature("drug_001", "dexamethasone", dex_up, dex_down),
    create_signature("drug_002", "budesonide", bud_up, bud_down),
    create_signature("drug_004", "tofacitinib", tof_up, tof_down),
    create_signature("drug_005", "ruxolitinib", rux_up, rux_down),
], ignore_index=True)

all_signatures.head(20)

   perturbation_id perturbation_name gene_symbol  rank_score
0         drug_001     dexamethasone       FKBP5          50
1         drug_001     dexamethasone     TSC22D3          49
2         drug_001     dexamethasone       DUSP1          48
3         drug_001     dexamethasone       DUSP4          47
4         drug_001     dexamethasone       DUSP5          46
5         drug_001     dexamethasone        KLF2          45
6         drug_001     dexamethasone        KLF4          44
7         drug_001     dexamethasone        PER1          43
8         drug_001     dexamethasone        SGK1          42
9         drug_001     dexamethasone       ZFP36          41
10        drug_001     dexamethasone      NFKBIA          40
11        drug_001     dexamethasone     TNFAIP3          39
12        drug_001     dexamethasone       SOCS1          38
13        drug_001     dexamethasone       SOCS2          37
14        drug_001     dexamethasone       SOCS3          36
15        drug_001     dexamethasone       IL1R2          35
16        drug_001     dexamethasone        GILZ          34
17        drug_001     dexamethasone        PDK4          33
18        drug_001     dexamethasone       CEBPD          32
19        drug_001     dexamethasone       CEBPB          31

## 7. Check how many genes each drug has

In [8]:
all_signatures.groupby("perturbation_id").size()

perturbation_id
drug_001    100
drug_002     91
drug_004     89
drug_005     71
dtype: int64

## 8. Save the final signatures file

In [9]:
all_signatures[["perturbation_id", "gene_symbol", "rank_score"]].to_csv(
    SIGNATURE_FILE,
    sep="\t",
    index=False
)

print("Saved:", SIGNATURE_FILE)

Saved: ../data/external/lincs/lincs_filtered_signatures.tsv

## 9. Make sure the manifest exists

In [10]:
manifest_check = pd.read_csv(MANIFEST_FILE, sep="\t")
manifest_check

,perturbation_id,perturbation_name,cell_line,dose,time_h,signature_source
0,drug_001,dexamethasone,NaN,NaN,NaN,curated_public_signature
1,drug_002,budesonide,NaN,NaN,NaN,curated_public_signature
2,drug_004,tofacitinib,NaN,NaN,NaN,curated_public_signature
3,drug_005,ruxolitinib,NaN,NaN,NaN,curated_public_signature

## 10. Verify the saved signature file

In [11]:
signature_check = pd.read_csv(SIGNATURE_FILE, sep="\t")
print(signature_check.head(15))
print()
print(signature_check.groupby("perturbation_id").size())

   perturbation_id gene_symbol  rank_score
0         drug_001       FKBP5          50
1         drug_001     TSC22D3          49
2         drug_001       DUSP1          48
3         drug_001       DUSP4          47
4         drug_001       DUSP5          46
5         drug_001        KLF2          45
6         drug_001        KLF4          44
7         drug_001        PER1          43
8         drug_001        SGK1          42
9         drug_001       ZFP36          41
10        drug_001      NFKBIA          40
11        drug_001     TNFAIP3          39
12        drug_001       SOCS1          38
13        drug_001       SOCS2          37
14        drug_001       SOCS3          36

perturbation_id
drug_001    100
drug_002     91
drug_004     89
drug_005     71
dtype: int64

## 11. Next step

Now rerun:

- `03_perturbation_gsea_lincs.ipynb`

This helper writes the exact file Step 3 expects:

- `data/external/lincs/lincs_filtered_signatures.tsv`

with columns:

- `perturbation_id`
- `gene_symbol`
- `rank_score`